# config.yaml

# This configuration file controls which modules are used
# in each step of the LiftOCR pipeline.

# Use full Python import paths to locate each class.
# These paths are relative to the project root.

# Preprocessing step
preprocessor: ocr.modules.preprocess.basic.BasicPreprocessor

# Segmentation step
segmenter: ocr.modules.segment.default.DefaultSegmenter

# Recognition step
recognizer: ocr.modules.recognize.model.ModelRecognizer
recognizer_engine: easyocr  # Options: easyocr, tesseract

# Postprocessing step
postprocessor: ocr.modules.postprocess.basic.BasicPostprocessor

# Output step
output: ocr.modules.output.text.TextOutput
output_path: output/   # Folder to save OCR result .txt files

# Optional future configuration options
log_level: INFO